 - name: On installe NTP
   yum:
     name: ntp
     state: present
   become: yes


 - name: On copie le fichier template
   copy:
     src: /etc/ansible/fichiers/ntp/ntp.conf
     dest: /etc/ntp.conf
     owner: root
     group: root
     mode: 0644

 - name: On demarre NTP
   service:
     name: ntpd
     state: started

 - name: On ajoute NTP dans systemD
   systemd:
     name: ntpd
     enabled: yes
     masked: no

