- hosts: Centos
  tasks:
  - name: Ansible register variable basic example
    shell: "find *.txt"
    args:
      chdir: "/var/cache/yum/x86_64/7/"
    register: find_output

  - debug:
      var: find_output.stdout
