---
- hosts: Centos
  gather_facts: no
  become: yes
  become_user: root
  roles:
  - resolv
  - ntp
  - apache2-yum
#  - changepassword
    #  - fichier
  - fail2ban
  - utilitaires
- import_playbook: glusterfs-client.yml
- import_playbook: sudoers.yml
