---
- hosts: Centos
  gather_facts: no
  roles:
  - resolv
  - ntp
  - apache2-yum
#  - changepassword
    #  - fichier
  - utilitaires
  - fail2ban
- import_playbook: glusterfs-client.yml
- import_playbook: sudoers.yml
