---
- hosts: Centos
  gather_facts: no
  tasks: 
#    - name: Install Nginx
#      yum: 
#        name: httpd
#        state: installed
#      notify:
#        - Start Nginx

#    - name: check le service
#      service: 
#        name: httpd
#        state: started
#      notify:
 #       - Start Nginx

    - name: On copie le fichier template
      copy:
        src: /etc/ansible/fichiers/fail2ban/jail.local.modif
        dest: /etc/fail2ban/jail.local
        owner: root
        group: root
        mode: 0644
      notify: Start Nginx

  handlers:
    - name: Start Nginx
      service:
        name: httpd
        state: started
