#- name: Install base packages
#  apt: name={{ apache2 }} state=installed
#  apt: pkg=w3m state=installed

# This uses a variable as this changes per distribution.
#- name: add the apache package
#  package:
#      name: "{{ w3m }}"
#      state: present

 - name : On installe Apache
   yum:
     name: httpd 
     state: present
   notify: httpd stopped

# - name : On demarre le service
#   service:
#     name: httpd
#     state: stopped

 - name : On ajoute le service dans systemD
   systemd:
     name: httpd
     enabled: no
     masked: no
