---
# tasks file for postfix-relais
- name : install postfix
  yum : 
    name: ['postfix', 'cyrus-sasl', 'cyrus-sasl-plain', 'mailx']
    state: present
  notify: restart postfix

- name: Copier le fichier main.cf
  template: 
    src: main.j2
    dest: /etc/postfix/main.cf
    mode: '0644'
  notify: restart postfix

# google app password appname = postfix
- name: Copier le fichier authentification
  template: 
    src: sasl_passwd.j2
    dest: /etc/postfix/sasl_passwd
    mode: '0644'
  notify: restart postfix
