 - name: On installe fail2ban
   yum:
     name: epel-release
     state: present

 - yum:
     name: fail2ban
     state: present

# copie fichier locale vers remote
 - name: On copie le fichier template
   copy:
     src: /etc/ansible/fichiers/fail2ban/jail.local.modif
     dest: /etc/fail2ban/jail.local
     owner: root
     group: root
     mode: 0644

# mets la bonne valeure
 - name: On mets le bon bantime dans le fichier
   lineinfile:
     path: /etc/fail2ban/jail.local
     regexp: '^bantime='
     line: 'bantime=600'
     backrefs: yes
     #     state: present

# mets la bonne valeure
 - name: On mets le bon findtime
   lineinfile:
     path: /etc/fail2ban/jail.local
     regexp: '^findtime='
     line: 'findtime=86400'
     state: present

 - service:
     name: fail2ban
     state: restarted

 - systemd:
     name: fail2ban
     enabled: yes
     masked: no

