 - name: On installe epel-release
   yum:
     name: epel-release
     state: present

 - name: On installe fail2ban
   yum:
     name: fail2ban
     state: present
   notify: fail2ban restarted

 - name: On copie le fichier template
   copy:
     src: /etc/ansible/fichiers/fail2ban/jail.local.modif
     dest: /etc/fail2ban/jail.local
     owner: root
     group: root
     mode: 0644
   notify: fail2ban restarted

 - name: On mets le bon bantime dans le fichier
   lineinfile:
     path: /etc/fail2ban/jail.local
     regexp: '^bantime='
     line: 'bantime=600'
     backrefs: yes
   notify: fail2ban restarted
     #     state: present

 - name: On mets le bon findtime
   lineinfile:
     path: /etc/fail2ban/jail.local
     regexp: '^findtime='
     line: 'findtime=86400'
     backrefs: yes
   notify: fail2ban restarted
     #state: present

# - name: On demarre fail2ban
#   service:
#     name: fail2ban
#     state: restarted

 - name: On ajoute fail2ban dans systemD
   systemd:
     name: fail2ban
     enabled: yes
     masked: no
